apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc
  description:
    $text: https://va.ghe.com/software/lighthouse-copilot/blob/main/_bmad/core/tasks/index-docs.xml
spec:
  type: service          # required for Component
  lifecycle: experimental # required for Component
  owner: guest            # required for Component
