apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc
  description:
    $text: https://va.ghe.com/software/code-va/blob/main/tsconfig.json
spec:
  type: service          # required for Component
  lifecycle: experimental # required for Component
  owner: guest            # required for Component
